config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  get 'activities/index'

  # mount ActionCable.server => "/"
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  
  resources :posts do 
    post 'share/:user_id', to: 'posts#share', as: 'share_post'
    resources :comments, only: [ :index, :create ]
  end
  
  resources :profile, only: [:show, :edit, :update, :destroy]
  
  # Custom Routes for Requests Handling
  get 'follow_requests', to: 'requests#follow_requests'
  get 'pending_requests', to: 'requests#pending_requests'
  get 'blocked_users', to: "requests#blocked_users"

  post 'requests/:id/follow', to: "requests#follow", as: "follow"
  post 'requests/:id/unfollow', to: "requests#unfollow", as: "unfollow"
  post 'requests/:id/accept', to: "requests#accept", as: "accept"
  post 'requests/:id/decline', to: "requests#decline", as: "decline"
  post 'requests/:id/cancel', to: "requests#cancel", as: "cancel"
  post 'requests/:id/block', to: "requests#block", as: "block"
  post 'requests/:id/unblock', to: "requests#unblock", as: "unblock"

  # Custom routes for profile search
  get 'search', to: "search#search"
  post 'search', to: "search#query" 

  # Likes Routes
  resources :likes, only: [:create, :destroy]

  # Activities Routes
  resources :activities, only: [:index]

  # Messsages Routes
  resources :messages, only: [:index, :create, :show]

  # Notification Management
  post "notifications/mark_all_pan_as_read", to: "notifications#mark_all_pan_as_read"
  post "notifications/mark_all_dm_as_read", to: "notifications#mark_all_dm_as_read"

  # Notification Preferences
  resources :notification_preferences, only: [:create, :destroy]

  # Story & Views
  resources :stories, only: [:create, :index, :show] do 
    collection do 
      get "my_stories"
    end
  end
  resources :story_views, only: [:create]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_danger.html.erb
<div class="alert alert-danger alert-dismissible fade show my-2 d-flex justify-content-between my-3 align-items-center" role="alert">
  <p><%= message %></p>

  <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show my-2 d-flex justify-content-between my-3 align-items-center" role="alert">
    <%= flash[:notice]%>
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<%end%>


<% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible fade show my-2 d-flex justify-content-between my-3 align-items-center" role="alert">
    <%= flash[:alert]%>
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<%end%>

app/views/shared/_navbar.html.erb
<%= stylesheet_link_tag "navbar" %>

<nav id="sidebarMenu" data-user-id="<%= active_user.id %>">
    <div class="brand" >
      <i class="fa-solid fa-mobile fa-fw"></i>
      <span class="fw-bold">GetSocial</span>
    </div>

    <div class="list-group">
      <%= link_to root_path, class: 'list-group-item list-group-item-action' do %>
        <i class="fa fa-home fa-fw"></i>
        <span>Home</span>
      <% end %>

      <%= link_to search_path, method: :get, class: 'list-group-item list-group-item-action' do %>
        <i class="fa fa-search fa-fw"></i>
        <span>Search</span>
      <% end %>

      <%= link_to activities_path, class: 'list-group-item list-group-item-action' do %>
        <i class="fa-solid fa-heart fa-fw"></i>
        <span  id="unread-notification-count"  class="<%=pan_badge_visibility%> badge bg-danger rounded-pill position-absolute top-0 start-100 translate-middle" data-user-id=<%= active_user.id %>>
          <%= pan_count %>
        </span>
        <span>Activity</span>
      <% end %>

      <%= link_to stories_path, method: :get, class: 'list-group-item list-group-item-action' do %>
        <i class="fa-solid fa-images"></i>
        <span>Stories</span>
      <% end %>

      <%= link_to messages_path, class: 'list-group-item list-group-item-action' do %>
        <i class="fa-solid fa-message fa-fw"></i>
        <span  id="unread-messages-count"  class="<%=msg_badge_visibility%> badge bg-danger rounded-pill position-absolute top-0 start-100 translate-middle" data-user-id=<%= active_user.id %>>
          <%= msg_count %>
        </span>
        <span>Messages</span>
      <% end %>

      <%= link_to root_path, class: 'list-group-item list-group-item-action', "data-bs-toggle"=>"modal", "data-bs-target"=>"#createPostModal" do %>
        <i class="fa fa-plus fa-fw"></i>
        <span>Create</span>
      <% end %>

      <%= link_to profile_path(current_user), method: :get, class: 'list-group-item list-group-item-action' do %>
        <i class="fa fa-user fa-fw"></i>
        <span>Profile</span>
      <% end %>
    </div>

    <div class="dropup-center dropup settings-dropup">
      <button class="w-100 btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fa fa-cog fa-fw me-3"></i><span>Settings</span>
      </button>
      <ul class="dropdown-menu">
        <li><%= button_to "Blocked Users", blocked_users_path, method: :get, class: "dropdown-item" %></li>
        <li><%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
      </ul>
    </div>

  </nav>

app/views/shared/_success.html.erb
<div class="alert alert-success alert-dismissible fade show my-2 d-flex justify-content-between my-3 align-items-center" role="alert">
  <p><%= message %></p>

  <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
  </button>
</div>