config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  get 'activities/index'

  # mount ActionCable.server => "/"
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  
  resources :posts do 
    post 'share/:user_id', to: 'posts#share', as: 'share_post'
    resources :comments, only: [ :index, :create ]
  end
  
  resources :profile, only: [:show, :edit, :update, :destroy]
  
  # Custom Routes for Requests Handling
  get 'follow_requests', to: 'requests#follow_requests'
  get 'pending_requests', to: 'requests#pending_requests'
  get 'blocked_users', to: "requests#blocked_users"

  post 'requests/:id/follow', to: "requests#follow", as: "follow"
  post 'requests/:id/unfollow', to: "requests#unfollow", as: "unfollow"
  post 'requests/:id/accept', to: "requests#accept", as: "accept"
  post 'requests/:id/decline', to: "requests#decline", as: "decline"
  post 'requests/:id/cancel', to: "requests#cancel", as: "cancel"
  post 'requests/:id/block', to: "requests#block", as: "block"
  post 'requests/:id/unblock', to: "requests#unblock", as: "unblock"

  # Custom routes for profile search
  get 'search', to: "search#search"
  post 'search', to: "search#query" 

  # Likes Routes
  resources :likes, only: [:create, :destroy]

  # Activities Routes
  resources :activities, only: [:index]

  # Messsages Routes
  resources :messages, only: [:index, :create, :show]

  # Notification Management
  post "notifications/mark_all_pan_as_read", to: "notifications#mark_all_pan_as_read"
  post "notifications/mark_all_dm_as_read", to: "notifications#mark_all_dm_as_read"

  # Notification Preferences
  resources :notification_preferences, only: [:create, :destroy]

  # Story & Views
  resources :stories, only: [:create, :index, :show] do 
    collection do 
      get "my_stories"
    end
  end
  resources :story_views, only: [:create]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
    include RequestsHelper
    before_action :set_user
    skip_before_action :set_user, only: [:follow_requests, :pending_requests, :blocked_users]

    def follow_requests
        @follow_requests = active_user.follow_requests
    end

    def pending_requests
        @pending_requests = active_user.pending_requests
    end

    def follow
        active_user.send_follow_request_to(@target)
        Notifier::Request.notify( "New follow request from: ", active_user.email, @target)
    end

    def unfollow
        active_user.unfollow(@target)
    end

    def cancel
        active_user.remove_follow_request_for(@target)
    end

    def accept
        active_user.accept_follow_request_of(@target)    
    end

    def decline
        active_user.decline_follow_request_of(@target)
    end

    def block
        active_user.block(@target)
        remove_connections_if_any(@target)
        redirect_to root_path
    end

    def unblock
        active_user.unblock(@target)
        redirect_to profile_path(@target)
    end

    def blocked_users
        @blocked_users = active_user.blocks
    end

    private
    def set_user
        @target = User.find(params[:id])
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
  def render_request_button_if_user_not_blocked(user)
    unless active_user.blocked?(user)
      yield
    end
  end

  def render_follow_button(user)
    if !active_user.following?(user) && !active_user.sent_follow_request_to?(user) 
      yield
    end
  end

  def render_cancel_request_button(user)
    if active_user.sent_follow_request_to?(user)
      yield
    end
  end

  def render_unfollow_button(user)
    if active_user.following?(user)
      yield
    end
  end

  def render_content_if_no_blocked_users(blocked_users_count)
    if blocked_users_count == 0 
      yield
    end
  end

  def render_blocked_users(blocked_users_count)
    unless blocked_users_count == 0 
      yield
    end
  end

  def render_requests_if_available(request_count)
    if request_count > 0 
        yield
    end
  end

  def render_content_if_available(request_count)
    unless request_count > 0 
        yield
    end
  end


  def remove_connections_if_any(user)

    if active_user.mutual_following_with?(user)
      active_user.unfollow(user)
      user.unfollow(active_user)
    elsif active_user.following?(user)
        active_user.unfollow(user)
    elsif user.following?(active_user)
        user.unfollow(active_user)
    end
    
  end

end

app/views/requests/_blocked_user.html.erb
<div class="grand-parent d-flex justify-centent-between align-items-center mb-3">
    <div class="user-details">
        <% if user.profile_picture.attached? %>
        <%= image_tag user.profile_picture, class: "posts-user-avatar" %>
        <% else %>
        <%= image_tag 'user_avatar.png', class: "posts-user-avatar" %>
        <% end %>
        <div>
            <h4><%= user.email%></h4>
            <h6><%= user.name%></h6>
        </div>
    </div>
    <button class="btn btn-lg btn-outline-dark unblock-btn" data-user-id=<%=user.id%>>Unblock</button>
</div>

app/views/requests/_pending_request.html.erb
<div>
    <div class="request-container">
        <div class="user-details">
            <% if user.profile_picture.attached? %>
            <%= image_tag user.profile_picture, class: "posts-user-avatar" %>
            <% else %>
            <%= image_tag 'user_avatar.png', class: "posts-user-avatar" %>
            <% end %>
            <div>
                <h4><%= user.email%></h4>
                <h6><%= user.name%></h6>
            </div>
        </div>

        <button class="btn btn-lg btn-outline-dark user-profile-btn accept w-25 cancel" data-user-id=<%=user.id%>>Cancel Request</button>
    </div>
    <hr/>
</div>


<script>

function AJAX(u_id, request_type){
    $.ajax({
        type: "post",
        url: `http://localhost:3000/requests/${u_id}/${request_type}`,
        data: "data",
        success: function (response) {
            console.log(response);
        }
    });
}

$(document).ready(() => {
    $(document).on("click", ".accept, .decline", (event) => {
        event.preventDefault();
        const button = $(event.target);
        const u_id = $(event.target).attr('data-user-id');
        
        AJAX(u_id, "cancel");

        $(event.target).parent().parent().empty()
    });
});
</script>

app/views/requests/_request_buttons.html.erb
<% render_request_button_if_user_not_blocked(user) do %>
    <% render_unfollow_button(user) do %>
        <div class="button-container">
            <%# button_to "Unfollow", unfollow_path(user), method: :post, class: "btn btn-lg btn-outline-dark user-profile-btn w-100 unfollow", 'data-user-id':user.id %>
            <button class="btn btn-lg btn-outline-dark user-profile-btn w-100 unfollow" data-user-id=<%=user.id%> >Unfollow</button>
        </div>
    <%end%>

    <% render_cancel_request_button(user) do %>
        <div class="button-container">
            <%# button_to "Cancel Request", cancel_path(user), method: :post, class: "btn btn-lg btn-outline-dark user-profile-btn w-100 cancel", 'data-user-id':user.id%>
            <button class="btn btn-lg btn-outline-dark user-profile-btn w-100 cancel" data-user-id=<%=user.id%> >Cancel Request</button>
        </div>
    <%end%>

    <% render_follow_button(user) do %>
        <div class="button-container">
            <%# button_to "Follow", follow_path(user), method: :post, class: "btn btn-lg btn-outline-dark user-profile-btn w-100 follow", 'data-user-id':user.id %>
            <button class="btn btn-lg btn-outline-dark user-profile-btn w-100 follow" data-user-id=<%=user.id%> >Follow</button>
        </div>
    <%end%>
<% end %>

app/views/requests/blocked_users.html.erb
<%= stylesheet_link_tag "blocks"%>

<%= javascript_include_tag "ajax_scripts/request_handler"%>

<div id="blocked-users-contianer">
    <%render_content_if_no_blocked_users(@blocked_users.count) do %>
        <h3 class="text-center mt-3"><em><strong>You have not blocked any uers, Go ahead and block the haters 😉</strong></em></h3>
    <%end%>

    <% render_blocked_users(@blocked_users.count)do  %>
        <% @blocked_users.each do |user|%>
            <%= render partial:"blocked_user", locals: {user: user} %>
        <% end %>
    <% end %>
</div>

app/views/requests/follow_requests.html.erb
<%= stylesheet_link_tag "requests" %>

<%= javascript_include_tag "ajax_scripts/request_handler"%>

<% render_content_if_available(@follow_requests.count) do %>
<h1 class='text-center'>No follow requests!!!</h1>
<% end %>

<% render_requests_if_available(@follow_requests.count) do %>
    <div id="all-follow-requests">
        <% @follow_requests.each do |follow_request|%>
            <% user = User.find(follow_request.followerable_id) %>
            <div class="following">
                <div class="request-container">
                    <div class="user-details">
                        <% if user.profile_picture.attached? %>
                        <%= image_tag user.profile_picture, class: "posts-user-avatar" %>
                        <% else %>
                        <%= image_tag 'user_avatar.png', class: "posts-user-avatar" %>
                        <% end %>
                        <div>
                            <h4><%= user.email%></h4>
                            <h6><%= user.name%></h6>
                        </div>
                    </div>

                    <div class="approval-button-column">
                        <button class="btn btn-sm btn-outline-dark user-profile-btn accept w-100" data-user-id=<%=user.id%>>Accept</button>

                        <button class="btn btn-sm  btn-outline-dark user-profile-btn decline w-100" data-user-id=<%=user.id%>>Decline</button>
                    </div>
                </div>
                <hr/>
            </div>
        <% end %>
    </div>
<% end %>

app/views/requests/pending_requests.html.erb
<%= stylesheet_link_tag "requests" %>

<%= javascript_include_tag "ajax_scripts/request_handler"%>

<% render_content_if_available(@pending_requests.count) do %>
    <h1 class='text-center'>No pending requests!!!</h1>
<% end %>

<% render_requests_if_available(@pending_requests.count) do %>
    <div id="all-pending-requests">
    <% @pending_requests.each do |pending_request|%>
        <% user = User.find(pending_request.followable_id) %>
        <div class="pending">
        <div class="request-container ">
            <div class="user-details">
                <% if user.profile_picture.attached? %>
                <%= image_tag user.profile_picture, class: "posts-user-avatar" %>
                <% else %>
                <%= image_tag 'user_avatar.png', class: "posts-user-avatar" %>
                <% end %>
                <div>
                    <h4><%= user.email%></h4>
                    <h6><%= user.name%></h6>
                </div>
            </div>

            <button class="btn btn-lg btn-outline-dark user-profile-btn accept w-25 cancel-pending-request" data-user-id=<%=user.id%>>Cancel Request</button>
        </div>
        <hr/>
        </div>
    <% end %>
    </div>
<% end %>