config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  get 'activities/index'

  # mount ActionCable.server => "/"
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  
  resources :posts do 
    post 'share/:user_id', to: 'posts#share', as: 'share_post'
    resources :comments, only: [ :index, :create ]
  end
  
  resources :profile, only: [:show, :edit, :update, :destroy]
  
  # Custom Routes for Requests Handling
  get 'follow_requests', to: 'requests#follow_requests'
  get 'pending_requests', to: 'requests#pending_requests'
  get 'blocked_users', to: "requests#blocked_users"

  post 'requests/:id/follow', to: "requests#follow", as: "follow"
  post 'requests/:id/unfollow', to: "requests#unfollow", as: "unfollow"
  post 'requests/:id/accept', to: "requests#accept", as: "accept"
  post 'requests/:id/decline', to: "requests#decline", as: "decline"
  post 'requests/:id/cancel', to: "requests#cancel", as: "cancel"
  post 'requests/:id/block', to: "requests#block", as: "block"
  post 'requests/:id/unblock', to: "requests#unblock", as: "unblock"

  # Custom routes for profile search
  get 'search', to: "search#search"
  post 'search', to: "search#query" 

  # Likes Routes
  resources :likes, only: [:create, :destroy]

  # Activities Routes
  resources :activities, only: [:index]

  # Messsages Routes
  resources :messages, only: [:index, :create, :show]

  # Notification Management
  post "notifications/mark_all_pan_as_read", to: "notifications#mark_all_pan_as_read"
  post "notifications/mark_all_dm_as_read", to: "notifications#mark_all_dm_as_read"

  # Notification Preferences
  resources :notification_preferences, only: [:create, :destroy]

  # Story & Views
  resources :stories, only: [:create, :index, :show] do 
    collection do 
      get "my_stories"
    end
  end
  resources :story_views, only: [:create]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/story.rb
class Story < ApplicationRecord
  has_one_attached :pic
  belongs_to :user
  has_many :story_views, dependent: :destroy
  
  before_create :valid_image
  before_validation :valid_image
  private

  def valid_image
      unless pic.attached?
          errors.add(:base,:invalid,message:"Story must have an iamge attachment.")
          throw(:abort)
      end
  end
end

app/models/story_view.rb
class StoryView < ApplicationRecord
  belongs_to :user
  belongs_to :story

  validates_uniqueness_of :user_id, scope: :story_id
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    before_action :set_story, only: [:show]
    
    def index
        @stories = Story.where(user_id: active_user.following.pluck(:id)).order("created_at DESC")
    end
    
    def create
        @story = Story.create(story_params)

        if @story.save
            flash[:notice]="Story has been successfully uploaded :)"
            redirect_to story_path(@story)
        else
            flash[:alert]= @story.errors.full_messages.to_sentence
            redirect_to profile_path(active_user)
        end
    end

    def show
    end

    def my_stories
        @stories = active_user.stories.includes(:pic_attachment)
    end

    private

    def set_story
        @story = Story.find(params[:id])
    end

    def story_params
        params.require(:story).permit(:pic).merge(user: active_user)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
    def view_story_link(story)
        if StoryView.find_by(user: active_user, story: story).nil?
            link_to "View Story", story, class: "view-story-btn link-dark", data: {"story-id": story.id}
        else
            link_to "View Again", story, class: "view-story-btn link-dark", data: {"story-id": story.id}
        end
    end


    def render_my_stories_if_present(stories)
        if stories.length > 0 
            yield
        end
    end

    def render_content_if_no_stories(stories)
        unless stories.length > 0 
            yield
        end
    end
end

app/views/stories/_create_story_modal.html.erb
<div class="modal fade" id="storiesModal" tabindex="-1" role="dialog" aria-labelledby="storiesModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="storiesModalTitle">Story</h5>
        <button type="button" class="close" data-bs-dismiss="modal" id="stories-modal-close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="story-modal-body">
        <%= form_for Story.new(), url: stories_path, method: :post, id: "create-story-form", data: { turbo: false } do |form| %>
          <div class="mb-3">
              <%= form.label :pic, class: "form-label text-capitalize" %>
              <%= form.file_field :pic, class: "form-control", id: "story-pic", required: true %>
          </div>

          <div class="text-center mt-4">
              <%= form.submit 'Share 📤', class: "btn btn-outline-dark w-100", id: "create-story-btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/stories/_story.html.erb
<div class="show-story-container">
    <h4 class="mb-3"><strong>Author:</strong> <%= story.user.email %></h4>
    <% if story.pic.attached? %>
        <div class="attachment-contianer">
            <%= image_tag story.pic %>
        </div>
    <% end %>

    <%if story.user == active_user %>
        <p class="text-center mt-3"><strong>👁️‍🗨️</strong> <%= story.views %></p>
    <% end %>
</div>

app/views/stories/index.html.erb
<%= javascript_include_tag "ajax_scripts/stories_handler"%>

<div class="d-flex align-items-center justify-content-between">
    <h1>View my stories</h1>
    <%= button_to "View", my_stories_stories_path, method: :get, class:"btn btn-outline-dark btn-lg" %>
</div>
<hr/>

<% @stories.each do |story|%>
    
        <div class="d-flex justify-content-between align-items-center">
            <p><u><strong><%= story.user.email %></strong></u> uploaded a new story on <u><%=story.created_at.to_s.split(" ")[0]%></u></p>
            <%= view_story_link(story) %>
        </div>
    
<% end %>

app/views/stories/my_stories.html.erb
<%= stylesheet_link_tag "stories" %>

<% render_my_stories_if_present(@stories) do %> 
    <% @stories.each do |story|%>
        <div class="d-flex justify-content-between align-items-center">
            <%= render partial: "story", locals:{ story: story}%>
        </div>
    <% end %>
<% end %>


<% render_content_if_no_stories(@stories) do %>
    <h1 class="text-center">You have no stories!!!</h1>
<% end %>

app/views/stories/show.html.erb
<%= stylesheet_link_tag "stories" %>

<%= render partial: "story", locals:{ story: @story}%>