config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  get 'activities/index'

  # mount ActionCable.server => "/"
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
  
  resources :posts do 
    post 'share/:user_id', to: 'posts#share', as: 'share_post'
    resources :comments, only: [ :index, :create ]
  end
  
  resources :profile, only: [:show, :edit, :update, :destroy]
  
  # Custom Routes for Requests Handling
  get 'follow_requests', to: 'requests#follow_requests'
  get 'pending_requests', to: 'requests#pending_requests'
  get 'blocked_users', to: "requests#blocked_users"

  post 'requests/:id/follow', to: "requests#follow", as: "follow"
  post 'requests/:id/unfollow', to: "requests#unfollow", as: "unfollow"
  post 'requests/:id/accept', to: "requests#accept", as: "accept"
  post 'requests/:id/decline', to: "requests#decline", as: "decline"
  post 'requests/:id/cancel', to: "requests#cancel", as: "cancel"
  post 'requests/:id/block', to: "requests#block", as: "block"
  post 'requests/:id/unblock', to: "requests#unblock", as: "unblock"

  # Custom routes for profile search
  get 'search', to: "search#search"
  post 'search', to: "search#query" 

  # Likes Routes
  resources :likes, only: [:create, :destroy]

  # Activities Routes
  resources :activities, only: [:index]

  # Messsages Routes
  resources :messages, only: [:index, :create, :show]

  # Notification Management
  post "notifications/mark_all_pan_as_read", to: "notifications#mark_all_pan_as_read"
  post "notifications/mark_all_dm_as_read", to: "notifications#mark_all_dm_as_read"

  # Notification Preferences
  resources :notification_preferences, only: [:create, :destroy]

  # Story & Views
  resources :stories, only: [:create, :index, :show] do 
    collection do 
      get "my_stories"
    end
  end
  resources :story_views, only: [:create]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @pending_requests_count = active_user.pending_requests.count
    @follow_requests_count = active_user.follow_requests.count

    @post_activity_notifications = active_user.notifications.newest_first.where(type: "PostActivityNotifier::Notification")
  end
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
    def render_view_btn_if_requests_Available(request_count)
        if request_count > 0 
            yield
        end
    end

    def do_not_render_view_btn_if_requests_Available(request_count)
        unless request_count > 0 
            yield
        end
    end


end

app/views/activities/_notification.html.erb
<div class="notification-container">
    <p><span><%= notification.sender %></span> <%= notification.message %></p>
    <%= link_to "View Post", notification.record, class: "view-post-btn link-dark", data: {"notification-event-id": notification.event.id} %>
</div>

app/views/activities/_post_activity_notification.html.erb
<div class="notification-container">
    <p><span><%= notification.sender %></span> <%= notification.message %></p>
    <%= link_to "View Post", notification.record, class: "view-post-btn link-dark", data: {"notification-event-id": notification.event.id} %>
</div>

app/views/activities/index.html.erb
<%= stylesheet_link_tag "requests" %>

<%= stylesheet_link_tag "notifications" %>
<%= javascript_include_tag "ajax_scripts/mark_notification_as_read"%>

<div class="activity-req-container follow-request-activity">
    <h3><%= pluralize(@follow_requests_count, "- Follow Request") %></h3>
    <% render_view_btn_if_requests_Available(@follow_requests_count) do %>
        <%= link_to "View", follow_requests_path, method: :get, class: "btn btn-md btn-outline-dark visible" %>
    <% end %>

    <% do_not_render_view_btn_if_requests_Available(@follow_requests_count) do %>
        <%= link_to "View", follow_requests_path, method: :get, class: "btn btn-md btn-outline-dark invisible" %>
    <% end %>
</div>

<div class="activity-req-container pending-request-activity">
    <h3><%= pluralize(@pending_requests_count, "- Pending Request") %></h3>
    <% render_view_btn_if_requests_Available(@pending_requests_count) do %>
        <%= link_to "View", pending_requests_path, method: :get, class: "btn btn-md btn-outline-dark visible" %>
    <% end %>

    <% do_not_render_view_btn_if_requests_Available(@pending_requests_count) do %>
        <%= link_to "View", pending_requests_path, method: :get, class: "btn btn-md btn-outline-dark invisible" %>
    <% end %>
    </div>

<hr/>

<div class="d-flex justify-content-between align-items-center mb-3">
    <h3>Post Activity Notifications</h3>
    <button id="mark-all-pan-as-read" class="btn btn-md btn-outline-dark">Mark As Read</button>
</div>

<hr/>

<div id="post-activity-notificaions-container">
    <% @post_activity_notifications.each do |notification| %>
        <% if notification.unread?%>
            <%= render partial: "post_activity_notification", locals: {notification: notification} %>
        <% end %>
    <% end %>
</div>